language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails6.gemfile

script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
sudo: false
cache: bundler
# Due to this issue, stil not resolved: travis-ci/travis-ci#8969
before_install:
  - gem update --system
  - gem install bundler
