language: ruby
rvm:
  - 2.6
  - 2.7

script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
